### ISSUE TITLE
Directives that change the shape of the data?

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#161]
Was having a play with a directive for doing groupBy

```
query {
    labourItems @groupBy(column: workTypeId) {          
      workTypeId
    }  	
}
```
which seemed basic enough
```

  public class GroupByDirectiveProcessor : DirectiveProcessor<GroupByArguments>
    {
        public override string Name {  get => "groupBy";  }

        public override string Description { get => "groups the results by col names"; }

        public override Expression? ProcessExpression(Expression expression, object? arguments)
        {
            var args = arguments as GroupByArguments;
            return GroupByMember(expression, args.column);
        }

        public Expression GroupByMember(Expression expression, string memberPath)
        {
            var parameter = Expression.Parameter(expression.Type.GetGenericArguments()[0], "x");

            var member = memberPath.Split('.')
                .Aggregate((Expression)parameter, Expression.PropertyOrField);
            
            var selector = Expression.Lambda(member, parameter);

            var groupByCall = Expression.Call(typeof(Queryable), "GroupBy",
                new Type[] { parameter.Type, member.Type },
                expression, Expression.Quote(selector));
        
            return groupByCall;
        }

        public override BaseGraphQLField? ProcessField(BaseGraphQLField field, object? arguments)
        {
            return field;
        }
    }

    public class GroupByArguments
    {
        public string column { get; set; }
    }
```

Now obviously I'm not dealing with the fact that you can't select random columns without some form of aggregation (which is why i'm just pulling back the column I'm grouping by currently)

Problem is the code explodes deep within EQL

ExpressionUtil.MakeSelectWithDynamicType

around line 420

MakeSelectWithDynamicType

```
var call = isQueryable ? MakeCallOnQueryable("Select", new Type[] { currentContextParam.Type, dynamicType }, baseExp, selector) :
                    MakeCallOnEnumerable("Select", new Type[] { currentContextParam.Type, dynamicType }, baseExp, selector);
```

currentContextParam.Type is a LabourItem instead of a Igrouping<labouritem>, currently trying to figure out if I can somehow change that type in the directive, or if 

currentContextParam.Type

just needs to be switched to 

baseExp.Type.GetGenericArguments()[0]

Any thoughts?

of course i'd also need to update the selector to take the IGrouping type also which makes me think i need to do this somewhere else in the code.

**Comment by bzbetty** [comment]
aware i could probably use a field extension instead, however wasn't sure if that could conditionally change the shape of the output either (pet peeve I have with the pagination at the moment, not that I have a solution either).

So maybe I should be using extension to start the grouping

```
query {
    labourItem(groupBy: workTypeId) {          
      workTypeId
      anotherField @sum
    }  	
}
```

then a directive to specify the aggregation type

but I kinda feel like i'd hit the exact same issue with IGrouping

**Comment by lukemurray** [comment]
I used to have code that did things like this. But I went down the road of supporting the GraphQL spec to make use of all the tooling.

GraphQL doesn't have support for things that change the shape of the defined schema. I wish they would introduce them. So adding things like this will/may break other tooling you use (generating types etc).

I have thought about bringing them back as an extra feature and noting that they are not technically GraphQL compliant.

Issue is the directive assumes the shape and parameter types will not change. We could look at expanding directive processor to support things like this. Otherwise I _think_ is is possible in a field extension, as that has access to everything needed and can change them.

Introspection likely wouldn't work as you expect as it will only know of 1 return type for the field but it actually has multiple.

I assume your pet peeve with paging is that if you do not supply paging arguments you just want a "flat" array of the entity?

If you're interested in keeping support for GraphQL (and tooling etc - e.g. we generate both Typescript and C# from queries / schema). You'd have to have 2 fields

```gql
type Query {
  labourItems: [LabourItem!]
  labourItemsGrouped(groupBy: GroupedLabourItemField): [GroupedLabourItem!]
}
```

or adding the field and type on the `LabourItem` so you end up with a query like so

```gql
{
   labourItems {
      groupBy {
         workTypeId { # we group by this field
            # selecting from IGrouping
            key # select the key
            connection { #could be named anything
              # fields you want from LabourItem
            }
         }
      }
   }
}
```

I really wish GraphQL spec introduced support for either methods (`labourItems.groupBy`) or allow directives that change the return type.

Anyway, could like get something working. I'd have to play with it myself. You best bet is field extensions right now.

**Comment by bzbetty** [comment]
> I assume your pet peeve with paging is that if you do not supply paging arguments you just want a "flat" array of the entity?

Yep that's exactly it.

> You best bet is field extensions right now.

yeah i'll probably go down that path, along with maybe a helper method that lets me add it easily to all fields / subfields.
