### ISSUE TITLE
Delegate Compile Cache

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#306]
Did a quick PoC to benchmark caching the output of .Compile() on lambda expressions based on the expression text hash, go the following results.

any thoughts? I think it seems like a promising idea, i'll try get a PR up tomorrow.

```
|                                            Method |        Job |              Toolchain | IterationCount | LaunchCount | WarmupCount |       Mean |       Error |    StdDev |     Median |
|-------------------------------------------------- |----------- |----------------------- |--------------- |------------ |------------ |-----------:|------------:|----------:|-----------:|
|                         Query_SingleObjectWithArg | Job-VKTTFD | InProcessEmitToolchain |        Default |     Default |     Default | 1,929.0 us |    99.39 us | 291.50 us | 1,887.3 us |
|                 Query_SingleObjectWithArg_NoCache | Job-VKTTFD | InProcessEmitToolchain |        Default |     Default |     Default | 1,412.8 us |    40.90 us | 119.95 us | 1,385.3 us |
|              Query_SingleObjectWithArg_QueryCache | Job-VKTTFD | InProcessEmitToolchain |        Default |     Default |     Default | 1,357.3 us |    26.16 us |  74.21 us | 1,354.6 us |
|           Query_SingleObjectWithArg_DelegateCache | Job-VKTTFD | InProcessEmitToolchain |        Default |     Default |     Default |   730.8 us |    14.17 us |  16.86 us |   730.2 us |
|                Query_SingleObjectWithArg_AllCache | Job-VKTTFD | InProcessEmitToolchain |        Default |     Default |     Default |   736.6 us |    14.54 us |  29.36 us |   736.7 us |
```

**Comment by lukemurray** [comment]
Where is the cached? There is a cache. It caches the first stage compile from a GQL string to `GraphQLDocument`. Which has most of the expression etc built.

The hash is built from the GQL Query without the variables, i.e. the `query` prop in the request:

```json
{
  "query": "{ thingThings { id } }",
  "variables": {...}
```
meaning the same cached query can be used and you swap in different variables.

The reason it doesn't cache the final expression is... struggling to remember! But maybe
- the way expressions are built to reference the variables as parameters may need to change to allow this
- Fields that require services. If using with EF it actually builds and executes 2 expressions one without service fields then another to bring them in

Either way, I'd be happy to explore this together more, a lot has changed since the original cache was put in. Let's start with a PR and I'll think of the breaking points to add a test for it.

**Comment by bzbetty** [comment]
new benchmark results on my work box

```
|                                  Method |     Mean |    Error |   StdDev |
|---------------------------------------- |---------:|---------:|---------:|
|       Query_SingleObjectWithArg_NoCache | 627.0 us | 12.45 us | 24.29 us |
|    Query_SingleObjectWithArg_QueryCache | 596.4 us |  6.50 us |  6.08 us |
| Query_SingleObjectWithArg_DelegateCache | 257.9 us |  2.40 us |  2.13 us |
|      Query_SingleObjectWithArg_AllCache | 222.2 us |  3.58 us |  3.17 us |
```

**Comment by bzbetty** [comment]
on reviewing the numbers and playing with it in a more realworld situtation, it's not really a noticable impact.

Guessing compilation of a lambda isn't that expensive.

**Comment by lukemurray** [comment]
Not compares to executing or fetching data (if you're using EF).
