### ISSUE TITLE
[minor] Why `Model` property is ignored instead of `Microsoft.EntityFrameworkCore.Metadata.IModel` type?

### ISSUE THREAD

**Issue by eharshosh** [EntityGraphQL/EntityGraphQL#376]
Hi,

I just started using this awesome library with existing, already-modeled entities.
Unfortunately many of my entities has a property named 'Model', which is ignored by default.
I figured that I can work around that by doing this:
```csharp
builder.Services.AddGraphQLSchema<MyDbContext>(options =>
{
    options.IgnoreTypes.Add(typeof(Microsoft.EntityFrameworkCore.Metadata.IModel));
    options.IgnoreProps.Remove("Model");
}
```

My question is - is there any reason not to make this the default behavior?

Thanks!

**Comment by lukemurray** [comment]
Yeh I’m all for using types vs the name but currently the library doesn’t have a dependency on any Entity Framework library.
________________________________
From: Eitan Har-Shoshanim ***@***.***>
Sent: Saturday, June 1, 2024 4:40:48 PM
To: EntityGraphQL/EntityGraphQL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EntityGraphQL/EntityGraphQL] [minor] Why `Model` property is ignored instead of `Microsoft.EntityFrameworkCore.Metadata.IModel` type? (Issue #376)


Hi,

I just started using this awesome library with existing, already-modeled entities.
Unfortunately many of my entities has a property named 'Model', which is ignored by default.
I figured that I can work around that by doing this:

builder.Services.AddGraphQLSchema<MyDbContext>(options =>
{
    options.IgnoreTypes.Add(typeof(Microsoft.EntityFrameworkCore.Metadata.IModel));
    options.IgnoreProps.Remove("Model");
}

My question is - is there any reason not to make this the default behavior?

Thanks!

**Comment by eharshosh** [comment]
Got it. thanks.
