### ISSUE TITLE
Using DTOs?

### ISSUE THREAD

**Issue by JohnGalt1717** [EntityGraphQL/EntityGraphQL#377]
Is there any way to use DTOs that don't directly expose your data model AND solve the Select before where problem?

I.e. automapper has AsDataSource() that handles the reversing of the mapping so that where clauses can be put before the select and thus solve the indexing and row locking issues that select before where causes.

Is there any guidance on how to do similar?

**Comment by lukemurray** [comment]
Current that is via the attributes and `SchemaBuilder` or the schema API.

If using `SchemaBuilder.FromObject<MyContext>()` you can use `[GraphQLField("renamedField")]` to change the name of the field in the GraphQL schema and `[GraphQLIgnore]` to ignore fields so they will not be in the GraphQL schema.

The schema object returned by `SchemaBuilder.FromObject<MyContext>()` lets you further customer fields, removing, adding, etc to the schema. Or you can start with a blank schema and build it up yourself. using what every type and field names you want.

```cs
var schema = new SchemaProvider<MyContext>();
schema.AddType<Person>("Thing", "Information about a person");

// add our root-level query field with an argument
schema.Query().AddField(
    "thing", // GQL field name
    new { // GQL field arguments
        id = ArgumentHelper.Required<int>()
    },
    (ctx, args) => ctx.People.FirstOrDefault(p => p.Id == args.id), // expression to map to your model
    "Fetch person by ID" // GQL field description
);
```

You basically add GQL types that map to your dotnet type and add the fields you want on those types with an expression that resolves that field.

Hope this helps. Also welcome anything to make it clearer or better to use.

**Comment by jhancock-taxa** [comment]
Ok.  It would be really great to see something that would use Expression Tree visitors to reverse a mapping, apply a where that was passed into the query, and then select on the projection back to the DTO.

This fixes the Select before where problem which breaks indexes and creates row locks by accident, and enables DTOs properly.

I.e. this is similar to AutoMapper AsDataSource() which allows a where as if it was coming from the DTO and then ProjectTo<DTO>() which can then be further .Selected, although even better would be to have a vistor for the ProjecTo that allow for only doing the mapping on the fields that were actually requested so that there wasn't a double select in the EF generated SQL command.

**Comment by lukemurray** [comment]
Sorry. I’ve never used automapper so I might be missing something.  This library does use expression trees, and it does build expressions by putting the where call before the select (or first/last) call for the same reasons you mention, to build an optimal expression for EF. 

Is there an issue you have where this is not happening that I can help with ?

**Comment by JohnGalt1717** [comment]
I personally was hoping for something similar to how it's handled in Odata which allows you to inject the Odata Context and then pull out the where, select and order by lamdas.

You can then just do this: DataContext.Contacts.AsDataSource().Where(oDataContext.Where).OrderBy(oDataContext.OrderBy).ProjectTo<DTOType>();

Then when the IQueryable is materialized, odata puts a further select on just the fields that the odata request was asking for.

This does several things, not the least of which is allow you to secure your app better, limit the possible footprint of any where and order bys so that they can't be used abusively in your GraphQL and limits the scope of the request overall as well.

**Comment by lukemurray** [comment]
Sorry, a full example may help me better understand the issue.

A couple of comments that may or may not help.

Reusing expression arguments like `.Where(myWhereExpressionUsedInManyPlaces)` is currently not supported because of how expressions work. If we provided our own `QueryableProvider` we could probably support it (have avoided this so far). Or via source generators perhaps.

If you want to apply certain where clauses to the data context that the graphql is executed against, EF supports this with [Query Filters](https://learn.microsoft.com/en-us/ef/core/querying/filters). Not sure if this is what you mean though.

I'm not sure where you want to pull out the where/order by etc to use them. This library takes a gql query and compiles to to expressions against a given data model (can be a DbContext). It also handles putting the `Select()` last. e.g.

```gql
query {
  movies {
    id name
    actors { name }
  }
}
```

will become

```cs
ctx => ctx.Movies.Select(m => new {
  id = m.Id,
  name = m.Name,
  actors = m.Actors.Select(a => new { name = a.Name })
});
```

If you want to be able to filter or order that you can use the filter and sort field extensions. If you don't want to use the `AddField/ReplaceField` methods to defined you schema and just want to use `SchemaBuilder.FromObject` you can use the attributes.

```cs
public class DemoContext : DbContext
{
    [UseFilter]
    [UseSort]
    public DbSet<Movie> Movies { get; set; }
}
```

Now

```gql
query {
  movies(filter: "releaseYear > 2000", sort: {name: ASC }) {
    id name
    actors { name }
  }
}
```

will become

```cs
ctx => ctx.Movies.Where(m => m.ReleaseYear > 2000).OrderBy(m => m.Name).Select(m => new {
  id = m.Id,
  name = m.Name,
  actors = m.Actors.Select(a => new { name = a.Name })
});
```

If you don't want to use EF Query Filters but want to change the expression used for the movies field you need to use the schema API as it is the way to define the full GraphQL schema.

```cs
schema.Query().ReplaceField("movies", ctx => ctx.Movies.Where(m => m.Deleted == false), "Field description");
```

That doesn't seem much different from the API in automapper like `CreateMap` and `FromMember` etc.

Again, I'm not 100% sure what you are trying to achieve so none of that may have helped you :)
