### ISSUE TITLE
Nested properties not loaded with Resolve<Service>()

### ISSUE THREAD

**Issue by ruigaspar** [EntityGraphQL/EntityGraphQL#379]
I have the following code and the only difference between them is the 'resolve', the first query doesn't resolve any service and the second one needs to resolve the AgeService but we don't do anything with it.

**Program.cs**
```
builder.Services.AddSingleton<IAgeService, AgeService>();
builder.Services.AddGraphQLSchema<DemoContext>(options => 
{
    options.ConfigureSchema = (schema) =>
    {
        schema.Query().AddField("testMovies1", "First movie").Resolve(ctx => ctx.Movies.First());
        schema.Query().AddField("testMovies2", "First movie").Resolve<IAgeService>((ctx, age) => ctx.Movies.First());
    };
});
```
**AgeService.cs**
```
public interface IAgeService
{
    int GetAge(DateTime dob);
}

public class AgeService : IAgeService
{
    public int GetAge(DateTime dob)
    {
        return (int)((DateTime.Now - dob).TotalDays / 365);
    }
}
```

When I call with this query, everything works fine:
*Query:*
```
{
    testMovies1 {
        id,
        name,
        director {
            id,
            firstName
        }
    }
}
```
*Response:*
```
{
    "data": {
        "testMovies1": {
            "id": 1,
            "name": "The Shawshank Redemption",
            "director": {
                "id": 2,
                "firstName": "Frank"
            }
        }
    }
}
```

But when I call with this query, all the nested properties are not included in the response, in this case the response doesen't include the `director `property:
*Query:*
```
{
    testMovies2 {
        id,
        name,
        director {
            id,
            firstName
        }
    }
}
```
*Response:*
```
{
    "data": {
        "testMovies2": {
            "id": 1,
            "name": "The Shawshank Redemption"
        }
    }
}
```

**Comment by lukemurray** [comment]
Is there any reason you need to set the fields up like that? This happens because services a resolve in memory after EF went and loaded data. And the director is not referenced or returned by EF so it is not there. I would expect a `null` or maybe an error though. To help demonstrate this.

`testMovies1` query turns into this

```cs
ctx => ctx.Movies.First().Select(m => new {
  id = m.Id,
  name = m.Name,
  director = new {
    id = m.Director.Id,
    firstName = m.Director.FirstName
  }
})
```

That is passed to EF which will fetch the director data. However `testMovies2` happens like this

```cs
ctx => ctx.Movies.First()
```

First pass, EF will fetch the first movie. No director data returned. Then it takes that data and executes with the expressions to resolve services which just returns the first movie again.

You either need to
- enable lazy loading
- have your field with the service do something. There are limitations so I would ask, what are you trying to do? Maybe I can help
