### ISSUE TITLE
Error Handling and Response Code

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#391]
Hi,

Is there a way to customize query responses/error, using in .net Core? If yes, is there a sample code or documentation avaialble. Please share the details.

**Comment by lukemurray** [comment]
Depends what you are trying to do. By default errors are generic to not leak any unwanted info. You can add certain exceptions that will be passed through if seen by using the [`AllowedExceptions` in the schema options](https://entitygraphql.github.io/docs/schema-creation/#building-a-full-schema).

If you mean HTTP codes you can build your [own controller](https://entitygraphql.github.io/docs/getting-started#custom-controller--manual-execution) and handle it there. Otherwise there are plans in 6.0 to have more control over error codes etc https://github.com/EntityGraphQL/EntityGraphQL/issues/331#issuecomment-2080387454

**Comment by lukemurray** [comment]
Have you added any exception to the `AllowedExceptions` list? It starts empty. This is to not leak any internal information about the system to attackers by default. If you have an exception you throw in a service field or a mutation that you want the API caller to see you add that exception to `AllowedExceptions` list.

In graphql errors end up in the `error` property of the resulting payload. EntityGraphQL will throw errors if the graphql document (the request) is not valid. It will throw errors if argument types do not match etc. If there is a user (non library) error throw it will list the field it happened within.

You can use [validation](https://entitygraphql.github.io/docs/validation) to trigger validation errors to

If you use the default AspNet setup example the HTTP error code will be
- 415 if the content type is wrong
- 400 is there is no content
- 400 if the result of the GQL contains any errors in the `errors` property
- otherwise 200

Currently only the error message is included in the error information in the payload.

**Comment by lukemurray** [comment]
Closing unless there is anything more you need. When we resolve #331 the HTTP codes will be more customisable and there is currently a way to get exception details through to the response .
